#!/bin/sh

entries="Reboot
Shutdown
Lock
Logout
Suspend"

selected=$(echo "$entries" | fuzzel --dmenu --prompt="Power:")

case $(echo "$selected" | awk '{print tolower($1)}') in
  lock)
    exec ~/.local/bin/scripts/lock.sh;;
  logout)
    swaymsg exit;;
  suspend)
    exec systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
esac
